// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Estado_SOAPBuilder implements SOAPInstanceBuilder {
    private clases.entidades.Estado _instance;
    private java.lang.String idEstado;
    private java.lang.String nombreEstado;
    private static final int myIDESTADO_INDEX = 0;
    private static final int myNOMBREESTADO_INDEX = 1;
    
    public Estado_SOAPBuilder() {
    }
    
    public void setIdEstado(java.lang.String idEstado) {
        this.idEstado = idEstado;
    }
    
    public void setNombreEstado(java.lang.String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myIDESTADO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myNOMBREESTADO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myIDESTADO_INDEX:
                    _instance.setIdEstado((java.lang.String)memberValue);
                    break;
                case myNOMBREESTADO_INDEX:
                    _instance.setNombreEstado((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (clases.entidades.Estado)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
