// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class EstudianteGrupo_SOAPBuilder implements SOAPInstanceBuilder {
    private clases.entidades.EstudianteGrupo _instance;
    private java.lang.String noExpediente;
    private java.lang.String PNombre;
    private java.lang.String SNombre;
    private java.lang.String PApellido;
    private java.lang.String SApellido;
    private java.lang.String CI;
    private java.lang.String idGrupo;
    private java.lang.String grupo;
    private java.lang.String idFacultad;
    private java.lang.String facultad;
    private static final int myNOEXPEDIENTE_INDEX = 0;
    private static final int myPNOMBRE_INDEX = 1;
    private static final int mySNOMBRE_INDEX = 2;
    private static final int myPAPELLIDO_INDEX = 3;
    private static final int mySAPELLIDO_INDEX = 4;
    private static final int myCI_INDEX = 5;
    private static final int myIDGRUPO_INDEX = 6;
    private static final int myGRUPO_INDEX = 7;
    private static final int myIDFACULTAD_INDEX = 8;
    private static final int myFACULTAD_INDEX = 9;
    
    public EstudianteGrupo_SOAPBuilder() {
    }
    
    public void setNoExpediente(java.lang.String noExpediente) {
        this.noExpediente = noExpediente;
    }
    
    public void setPNombre(java.lang.String PNombre) {
        this.PNombre = PNombre;
    }
    
    public void setSNombre(java.lang.String SNombre) {
        this.SNombre = SNombre;
    }
    
    public void setPApellido(java.lang.String PApellido) {
        this.PApellido = PApellido;
    }
    
    public void setSApellido(java.lang.String SApellido) {
        this.SApellido = SApellido;
    }
    
    public void setCI(java.lang.String CI) {
        this.CI = CI;
    }
    
    public void setIdGrupo(java.lang.String idGrupo) {
        this.idGrupo = idGrupo;
    }
    
    public void setGrupo(java.lang.String grupo) {
        this.grupo = grupo;
    }
    
    public void setIdFacultad(java.lang.String idFacultad) {
        this.idFacultad = idFacultad;
    }
    
    public void setFacultad(java.lang.String facultad) {
        this.facultad = facultad;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myNOEXPEDIENTE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPNOMBRE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySNOMBRE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPAPELLIDO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySAPELLIDO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCI_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myIDGRUPO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myGRUPO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myIDFACULTAD_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myFACULTAD_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myNOEXPEDIENTE_INDEX:
                    _instance.setNoExpediente((java.lang.String)memberValue);
                    break;
                case myPNOMBRE_INDEX:
                    _instance.setPNombre((java.lang.String)memberValue);
                    break;
                case mySNOMBRE_INDEX:
                    _instance.setSNombre((java.lang.String)memberValue);
                    break;
                case myPAPELLIDO_INDEX:
                    _instance.setPApellido((java.lang.String)memberValue);
                    break;
                case mySAPELLIDO_INDEX:
                    _instance.setSApellido((java.lang.String)memberValue);
                    break;
                case myCI_INDEX:
                    _instance.setCI((java.lang.String)memberValue);
                    break;
                case myIDGRUPO_INDEX:
                    _instance.setIdGrupo((java.lang.String)memberValue);
                    break;
                case myGRUPO_INDEX:
                    _instance.setGrupo((java.lang.String)memberValue);
                    break;
                case myIDFACULTAD_INDEX:
                    _instance.setIdFacultad((java.lang.String)memberValue);
                    break;
                case myFACULTAD_INDEX:
                    _instance.setFacultad((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (clases.entidades.EstudianteGrupo)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
