// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class EstudianteGrupo_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_NoExpediente_QNAME = new QName("", "NoExpediente");
    private static final javax.xml.namespace.QName ns3_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns3_myns3_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_PNombre_QNAME = new QName("", "PNombre");
    private static final javax.xml.namespace.QName ns1_SNombre_QNAME = new QName("", "SNombre");
    private static final javax.xml.namespace.QName ns1_PApellido_QNAME = new QName("", "PApellido");
    private static final javax.xml.namespace.QName ns1_SApellido_QNAME = new QName("", "SApellido");
    private static final javax.xml.namespace.QName ns1_CI_QNAME = new QName("", "CI");
    private static final javax.xml.namespace.QName ns1_IdGrupo_QNAME = new QName("", "IdGrupo");
    private static final javax.xml.namespace.QName ns1_Grupo_QNAME = new QName("", "Grupo");
    private static final javax.xml.namespace.QName ns1_IdFacultad_QNAME = new QName("", "IdFacultad");
    private static final javax.xml.namespace.QName ns1_Facultad_QNAME = new QName("", "Facultad");
    private static final int myNOEXPEDIENTE_INDEX = 0;
    private static final int myPNOMBRE_INDEX = 1;
    private static final int mySNOMBRE_INDEX = 2;
    private static final int myPAPELLIDO_INDEX = 3;
    private static final int mySAPELLIDO_INDEX = 4;
    private static final int myCI_INDEX = 5;
    private static final int myIDGRUPO_INDEX = 6;
    private static final int myGRUPO_INDEX = 7;
    private static final int myIDFACULTAD_INDEX = 8;
    private static final int myFACULTAD_INDEX = 9;
    
    public EstudianteGrupo_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns3_myns3_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.String.class, ns3_string_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        clases.entidades.EstudianteGrupo instance = new clases.entidades.EstudianteGrupo();
        wspregrado.EstudianteGrupo_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        for (int i=0; i<10; i++) {
            elementName = reader.getName();
            if (reader.getState() == XMLReader.END) {
                break;
            }
            if (elementName.equals(ns1_NoExpediente_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_NoExpediente_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myNOEXPEDIENTE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setNoExpediente((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_PNombre_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_PNombre_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPNOMBRE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPNombre((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_SNombre_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_SNombre_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySNOMBRE_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setSNombre((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_PApellido_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_PApellido_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myPAPELLIDO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setPApellido((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_SApellido_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_SApellido_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, mySAPELLIDO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setSApellido((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_CI_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_CI_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myCI_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setCI((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_IdGrupo_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_IdGrupo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myIDGRUPO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIdGrupo((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Grupo_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_Grupo_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myGRUPO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setGrupo((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_IdFacultad_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_IdFacultad_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myIDFACULTAD_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setIdFacultad((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            }
            if (elementName.equals(ns1_Facultad_QNAME)) {
                member = ns3_myns3_string__java_lang_String_String_Serializer.deserialize(ns1_Facultad_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.EstudianteGrupo_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFACULTAD_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFacultad((java.lang.String)member);
                }
                reader.nextElementContent();
                continue;
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_Facultad_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        clases.entidades.EstudianteGrupo instance = (clases.entidades.EstudianteGrupo)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        clases.entidades.EstudianteGrupo instance = (clases.entidades.EstudianteGrupo)obj;
        
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getNoExpediente(), ns1_NoExpediente_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPNombre(), ns1_PNombre_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getSNombre(), ns1_SNombre_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getPApellido(), ns1_PApellido_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getSApellido(), ns1_SApellido_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getCI(), ns1_CI_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getIdGrupo(), ns1_IdGrupo_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getGrupo(), ns1_Grupo_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getIdFacultad(), ns1_IdFacultad_QNAME, null, writer, context);
        ns3_myns3_string__java_lang_String_String_Serializer.serialize(instance.getFacultad(), ns1_Facultad_QNAME, null, writer, context);
    }
}
