// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Estudiante_SOAPBuilder implements SOAPInstanceBuilder {
    private clases.entidades.Estudiante _instance;
    private java.lang.String idExpediente;
    private java.lang.String primerNombre;
    private java.lang.String segundoNombre;
    private java.lang.String primerApellido;
    private java.lang.String segundoApellido;
    private java.lang.String CI;
    private clases.entidades.Estado estado;
    private java.lang.String genero;
    private clases.entidades.Municipio municipio;
    private clases.entidades.CategoriaPersona categoriaPersona;
    private clases.entidades.Area area;
    private clases.entidades.Grupo grupo;
    private clases.entidades.Nivel nivel;
    private static final int myIDEXPEDIENTE_INDEX = 0;
    private static final int myPRIMERNOMBRE_INDEX = 1;
    private static final int mySEGUNDONOMBRE_INDEX = 2;
    private static final int myPRIMERAPELLIDO_INDEX = 3;
    private static final int mySEGUNDOAPELLIDO_INDEX = 4;
    private static final int myCI_INDEX = 5;
    private static final int myESTADO_INDEX = 6;
    private static final int myGENERO_INDEX = 7;
    private static final int myMUNICIPIO_INDEX = 8;
    private static final int myCATEGORIAPERSONA_INDEX = 9;
    private static final int myAREA_INDEX = 10;
    private static final int myGRUPO_INDEX = 11;
    private static final int myNIVEL_INDEX = 12;
    
    public Estudiante_SOAPBuilder() {
    }
    
    public void setIdExpediente(java.lang.String idExpediente) {
        this.idExpediente = idExpediente;
    }
    
    public void setPrimerNombre(java.lang.String primerNombre) {
        this.primerNombre = primerNombre;
    }
    
    public void setSegundoNombre(java.lang.String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    
    public void setPrimerApellido(java.lang.String primerApellido) {
        this.primerApellido = primerApellido;
    }
    
    public void setSegundoApellido(java.lang.String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    
    public void setCI(java.lang.String CI) {
        this.CI = CI;
    }
    
    public void setEstado(clases.entidades.Estado estado) {
        this.estado = estado;
    }
    
    public void setGenero(java.lang.String genero) {
        this.genero = genero;
    }
    
    public void setMunicipio(clases.entidades.Municipio municipio) {
        this.municipio = municipio;
    }
    
    public void setCategoriaPersona(clases.entidades.CategoriaPersona categoriaPersona) {
        this.categoriaPersona = categoriaPersona;
    }
    
    public void setArea(clases.entidades.Area area) {
        this.area = area;
    }
    
    public void setGrupo(clases.entidades.Grupo grupo) {
        this.grupo = grupo;
    }
    
    public void setNivel(clases.entidades.Nivel nivel) {
        this.nivel = nivel;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myIDEXPEDIENTE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPRIMERNOMBRE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySEGUNDONOMBRE_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myPRIMERAPELLIDO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case mySEGUNDOAPELLIDO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCI_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myESTADO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myGENERO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myMUNICIPIO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myCATEGORIAPERSONA_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myAREA_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myGRUPO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myNIVEL_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myIDEXPEDIENTE_INDEX:
                    _instance.setIdExpediente((java.lang.String)memberValue);
                    break;
                case myPRIMERNOMBRE_INDEX:
                    _instance.setPrimerNombre((java.lang.String)memberValue);
                    break;
                case mySEGUNDONOMBRE_INDEX:
                    _instance.setSegundoNombre((java.lang.String)memberValue);
                    break;
                case myPRIMERAPELLIDO_INDEX:
                    _instance.setPrimerApellido((java.lang.String)memberValue);
                    break;
                case mySEGUNDOAPELLIDO_INDEX:
                    _instance.setSegundoApellido((java.lang.String)memberValue);
                    break;
                case myCI_INDEX:
                    _instance.setCI((java.lang.String)memberValue);
                    break;
                case myESTADO_INDEX:
                    _instance.setEstado((clases.entidades.Estado)memberValue);
                    break;
                case myGENERO_INDEX:
                    _instance.setGenero((java.lang.String)memberValue);
                    break;
                case myMUNICIPIO_INDEX:
                    _instance.setMunicipio((clases.entidades.Municipio)memberValue);
                    break;
                case myCATEGORIAPERSONA_INDEX:
                    _instance.setCategoriaPersona((clases.entidades.CategoriaPersona)memberValue);
                    break;
                case myAREA_INDEX:
                    _instance.setArea((clases.entidades.Area)memberValue);
                    break;
                case myGRUPO_INDEX:
                    _instance.setGrupo((clases.entidades.Grupo)memberValue);
                    break;
                case myNIVEL_INDEX:
                    _instance.setNivel((clases.entidades.Nivel)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (clases.entidades.Estudiante)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
