// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class Grupo_SOAPBuilder implements SOAPInstanceBuilder {
    private clases.entidades.Grupo _instance;
    private java.lang.String idGrupo;
    private java.lang.String nombreGrupo;
    private static final int myIDGRUPO_INDEX = 0;
    private static final int myNOMBREGRUPO_INDEX = 1;
    
    public Grupo_SOAPBuilder() {
    }
    
    public void setIdGrupo(java.lang.String idGrupo) {
        this.idGrupo = idGrupo;
    }
    
    public void setNombreGrupo(java.lang.String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myIDGRUPO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            case myNOMBREGRUPO_INDEX:
                return GATES_INITIALIZATION | REQUIRES_CREATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myIDGRUPO_INDEX:
                    _instance.setIdGrupo((java.lang.String)memberValue);
                    break;
                case myNOMBREGRUPO_INDEX:
                    _instance.setNombreGrupo((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (clases.entidades.Grupo)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
