// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.namespace.QName;

public class PregradoService_Impl extends com.sun.xml.rpc.client.BasicService implements PregradoService {
    private static final QName serviceName = new QName("urn:pregrado", "pregradoService");
    private static final QName ns1_ws_pregradoPort_QNAME = new QName("urn:pregrado", "ws_pregradoPort");
    private static final Class ws_pregradoPortType_PortClass = wspregrado.Ws_pregradoPortType.class;
    
    public PregradoService_Impl() {
        super(serviceName, new QName[] {
                        ns1_ws_pregradoPort_QNAME
                    },
            new wspregrado.PregradoService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_ws_pregradoPort_QNAME) &&
                serviceDefInterface.equals(ws_pregradoPortType_PortClass)) {
                return getWs_pregradoPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(ws_pregradoPortType_PortClass)) {
                return getWs_pregradoPort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public wspregrado.Ws_pregradoPortType getWs_pregradoPort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_ws_pregradoPort_QNAME));
        handlerChain.setRoles(roles);
        wspregrado.Ws_pregradoPortType_Stub stub = new wspregrado.Ws_pregradoPortType_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
