// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class PregradoService_SerializerRegistry implements SerializerConstants {
    public PregradoService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("urn:pregrado", "ObtenerFacultadDadoIdArea");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerNivelDadoIdNivelResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerGruposDadoIdArea");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoFiltroResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerGruposResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerGrupos_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerGrupos_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "EstadoArray");
            QName elemName = new QName("", "item");
            QName elemType = new QName("urn:pregrado", "Estado");
            CombinedSerializer serializer = new ObjectArraySerializer2(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING , 
                elemName, elemType, clases.entidades.Estado.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Estado[].class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "Municipio");
            CombinedSerializer serializer = new wspregrado.Municipio_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Municipio.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerGrupoDadoIdGrupoResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoCadenaBusquedaResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerFacultadDadoIdAreaResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerNivelesResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerNiveles_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerNiveles_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerFacultades");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerFacultades_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerFacultades_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerNiveles");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerNiveles_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerNiveles_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "CategoriaPersona");
            CombinedSerializer serializer = new wspregrado.CategoriaPersona_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.CategoriaPersona.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "Estado");
            CombinedSerializer serializer = new wspregrado.Estado_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Estado.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "EstudianteGrupoArray");
            QName elemName = new QName("", "item");
            QName elemType = new QName("urn:pregrado", "EstudianteGrupo");
            CombinedSerializer serializer = new ObjectArraySerializer2(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING , 
                elemName, elemType, clases.entidades.EstudianteGrupo.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.EstudianteGrupo[].class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudianteDadoCIResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudianteDadoIdExpedienteResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "Estudiante");
            CombinedSerializer serializer = new wspregrado.Estudiante_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Estudiante.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerGrupoDadoIdGrupo");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdGrupo");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "Area");
            CombinedSerializer serializer = new wspregrado.Area_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Area.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdExpedienteProfesorResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "EstudianteArray");
            QName elemName = new QName("", "item");
            QName elemType = new QName("urn:pregrado", "Estudiante");
            CombinedSerializer serializer = new ObjectArraySerializer2(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING , 
                elemName, elemType, clases.entidades.Estudiante.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Estudiante[].class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerNivelDadoIdNivel");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "NivelArray");
            QName elemName = new QName("", "item");
            QName elemType = new QName("urn:pregrado", "Nivel");
            CombinedSerializer serializer = new ObjectArraySerializer2(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING , 
                elemName, elemType, clases.entidades.Nivel.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Nivel[].class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "GrupoArray");
            QName elemName = new QName("", "item");
            QName elemType = new QName("urn:pregrado", "Grupo");
            CombinedSerializer serializer = new ObjectArraySerializer2(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING , 
                elemName, elemType, clases.entidades.Grupo.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Grupo[].class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerGrupos");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerGrupos_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerGrupos_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstadosResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstados_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstados_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoCadenaBusqueda");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoFiltro");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerFacultadesResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerFacultades_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerFacultades_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "AreaArray");
            QName elemName = new QName("", "item");
            QName elemType = new QName("urn:pregrado", "Area");
            CombinedSerializer serializer = new ObjectArraySerializer2(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING , 
                elemName, elemType, clases.entidades.Area.class, 1, null, SOAPVersion.SOAP_11);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Area[].class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerGruposDadoIdAreaResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstados");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstados_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstados_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "EstudianteGrupo");
            CombinedSerializer serializer = new wspregrado.EstudianteGrupo_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.EstudianteGrupo.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdGrupoResponse");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "Nivel");
            CombinedSerializer serializer = new wspregrado.Nivel_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Nivel.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "Grupo");
            CombinedSerializer serializer = new wspregrado.Grupo_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,clases.entidades.Grupo.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudianteDadoIdExpediente");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudianteDadoCI");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantes");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdExpedienteProfesor");
            CombinedSerializer serializer = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
