// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import javax.xml.rpc.*;

public interface PregradoService extends javax.xml.rpc.Service {
    public wspregrado.Ws_pregradoPortType getWs_pregradoPort() throws ServiceException;
}
