// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct {
    protected clases.entidades.Estudiante[] obtenerEstudiantesDadoFiltroReturn;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct(clases.entidades.Estudiante[] obtenerEstudiantesDadoFiltroReturn) {
        this.obtenerEstudiantesDadoFiltroReturn = obtenerEstudiantesDadoFiltroReturn;
    }
    
    public clases.entidades.Estudiante[] getObtenerEstudiantesDadoFiltroReturn() {
        return obtenerEstudiantesDadoFiltroReturn;
    }
    
    public void setObtenerEstudiantesDadoFiltroReturn(clases.entidades.Estudiante[] obtenerEstudiantesDadoFiltroReturn) {
        this.obtenerEstudiantesDadoFiltroReturn = obtenerEstudiantesDadoFiltroReturn;
    }
}
