// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

public interface Ws_pregradoPortType extends java.rmi.Remote {
    public clases.entidades.Estado[] obtenerEstados() throws 
         java.rmi.RemoteException;
    public clases.entidades.Estudiante obtenerEstudianteDadoCI(java.lang.String CI) throws 
         java.rmi.RemoteException;
    public clases.entidades.Estudiante obtenerEstudianteDadoIdExpediente(java.lang.String idExpediente) throws 
         java.rmi.RemoteException;
    public clases.entidades.Estudiante[] obtenerEstudiantes() throws 
         java.rmi.RemoteException;
    public clases.entidades.Estudiante[] obtenerEstudiantesDadoCadenaBusqueda(java.lang.String cadena) throws 
         java.rmi.RemoteException;
    public clases.entidades.Estudiante[] obtenerEstudiantesDadoFiltro(java.lang.Object filtro) throws 
         java.rmi.RemoteException;
    public clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdExpedienteProfesor(java.lang.String idExpedienteProfesor) throws 
         java.rmi.RemoteException;
    public clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdGrupo(java.lang.String idGrupo) throws 
         java.rmi.RemoteException;
    public clases.entidades.Area obtenerFacultadDadoIdArea(java.lang.String idArea) throws 
         java.rmi.RemoteException;
    public clases.entidades.Area[] obtenerFacultades() throws 
         java.rmi.RemoteException;
    public clases.entidades.Grupo obtenerGrupoDadoIdGrupo(java.lang.String idGrupo) throws 
         java.rmi.RemoteException;
    public clases.entidades.Grupo[] obtenerGrupos() throws 
         java.rmi.RemoteException;
    public clases.entidades.Grupo[] obtenerGruposDadoIdArea(java.lang.String idArea) throws 
         java.rmi.RemoteException;
    public clases.entidades.Nivel obtenerNivelDadoIdNivel(java.lang.String idNivel) throws 
         java.rmi.RemoteException;
    public clases.entidades.Nivel[] obtenerNiveles() throws 
         java.rmi.RemoteException;
}
