// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct {
    protected clases.entidades.Grupo obtenerGrupoDadoIdGrupoReturn;
    
    public Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct(clases.entidades.Grupo obtenerGrupoDadoIdGrupoReturn) {
        this.obtenerGrupoDadoIdGrupoReturn = obtenerGrupoDadoIdGrupoReturn;
    }
    
    public clases.entidades.Grupo getObtenerGrupoDadoIdGrupoReturn() {
        return obtenerGrupoDadoIdGrupoReturn;
    }
    
    public void setObtenerGrupoDadoIdGrupoReturn(clases.entidades.Grupo obtenerGrupoDadoIdGrupoReturn) {
        this.obtenerGrupoDadoIdGrupoReturn = obtenerGrupoDadoIdGrupoReturn;
    }
}
