// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPSerializer extends ObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_Filtro_QNAME = new QName("", "Filtro");
    private static final javax.xml.namespace.QName ns3_anyType_TYPE_QNAME = SchemaConstants.QNAME_TYPE_URTYPE;
    private CombinedSerializer ns3_myns3_anyType__DynamicSerializer;
    private static final int myFILTRO_INDEX = 0;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPSerializer(QName type, boolean encodeType, boolean isNullable, String encodingStyle) {
        super(type, encodeType, isNullable, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws java.lang.Exception {
        ns3_myns3_anyType__DynamicSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, java.lang.Object.class, ns3_anyType_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(SOAPDeserializationState state, XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct instance = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct();
        wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPBuilder builder = null;
        java.lang.Object member;
        boolean isComplete = true;
        javax.xml.namespace.QName elementName;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_Filtro_QNAME)) {
                member = ns3_myns3_anyType__DynamicSerializer.deserialize(ns1_Filtro_QNAME, reader, context);
                if (member instanceof SOAPDeserializationState) {
                    if (builder == null) {
                        builder = new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPBuilder();
                    }
                    state = registerWithMemberState(instance, state, member, myFILTRO_INDEX, builder);
                    isComplete = false;
                } else {
                    instance.setFiltro((java.lang.Object)member);
                }
                reader.nextElementContent();
            } else {
                throw new DeserializationException("soap.unexpectedElementName", new Object[] {ns1_Filtro_QNAME, elementName});
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (isComplete ? (java.lang.Object)instance : (java.lang.Object)state);
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct instance = (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct)obj;
        
    }
    
    public void doSerializeInstance(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct instance = (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct)obj;
        
        ns3_myns3_anyType__DynamicSerializer.serialize(instance.getFiltro(), ns1_Filtro_QNAME, null, writer, context);
    }
}
