// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct {
    protected clases.entidades.Grupo[] obtenerGruposDadoIdAreaReturn;
    
    public Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct(clases.entidades.Grupo[] obtenerGruposDadoIdAreaReturn) {
        this.obtenerGruposDadoIdAreaReturn = obtenerGruposDadoIdAreaReturn;
    }
    
    public clases.entidades.Grupo[] getObtenerGruposDadoIdAreaReturn() {
        return obtenerGruposDadoIdAreaReturn;
    }
    
    public void setObtenerGruposDadoIdAreaReturn(clases.entidades.Grupo[] obtenerGruposDadoIdAreaReturn) {
        this.obtenerGruposDadoIdAreaReturn = obtenerGruposDadoIdAreaReturn;
    }
}
