// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerFacultades_ResponseStruct {
    protected clases.entidades.Area[] obtenerFacultadesReturn;
    
    public Ws_pregradoPortType_ObtenerFacultades_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerFacultades_ResponseStruct(clases.entidades.Area[] obtenerFacultadesReturn) {
        this.obtenerFacultadesReturn = obtenerFacultadesReturn;
    }
    
    public clases.entidades.Area[] getObtenerFacultadesReturn() {
        return obtenerFacultadesReturn;
    }
    
    public void setObtenerFacultadesReturn(clases.entidades.Area[] obtenerFacultadesReturn) {
        this.obtenerFacultadesReturn = obtenerFacultadesReturn;
    }
}
