// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct {
    protected clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdExpedienteProfesorReturn;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct(clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdExpedienteProfesorReturn) {
        this.obtenerEstudiantesDadoIdExpedienteProfesorReturn = obtenerEstudiantesDadoIdExpedienteProfesorReturn;
    }
    
    public clases.entidades.EstudianteGrupo[] getObtenerEstudiantesDadoIdExpedienteProfesorReturn() {
        return obtenerEstudiantesDadoIdExpedienteProfesorReturn;
    }
    
    public void setObtenerEstudiantesDadoIdExpedienteProfesorReturn(clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdExpedienteProfesorReturn) {
        this.obtenerEstudiantesDadoIdExpedienteProfesorReturn = obtenerEstudiantesDadoIdExpedienteProfesorReturn;
    }
}
