// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstados_RequestStruct {
    
    public Ws_pregradoPortType_ObtenerEstados_RequestStruct() {
    }
}
