// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;

import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;

public class Ws_pregradoPortType_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements wspregrado.Ws_pregradoPortType {
    
    
    
    /*
     *  public constructor
     */
    public Ws_pregradoPortType_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        //   _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://localhost:8080");
     _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://pregrado.uci.cu/v1/ws_pregrado.php");
    }
    
    
    /*
     *  implementation of obtenerEstudiantesDadoCadenaBusqueda
     */
    public clases.entidades.Estudiante[] obtenerEstudiantesDadoCadenaBusqueda(java.lang.String cadena)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudiantesDadoCadenaBusqueda_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct.setCadena(cadena);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoCadenaBusqueda_ObtenerEstudiantesDadoCadenaBusqueda_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct.getObtenerEstudiantesDadoCadenaBusquedaReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstados
     */
    public clases.entidades.Estado[] obtenerEstados()
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstados_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstados_RequestStruct _myWs_pregradoPortType_ObtenerEstados_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstados_RequestStruct();
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstados_ObtenerEstados_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstados_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstados_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstados_ResponseStruct _myWs_pregradoPortType_ObtenerEstados_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstados_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstados_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstados_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstados_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstados_ResponseStruct.getObtenerEstadosReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstudianteDadoIdExpediente
     */
    public clases.entidades.Estudiante obtenerEstudianteDadoIdExpediente(java.lang.String idExpediente)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudianteDadoIdExpediente_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct _myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct.setIdExpediente(idExpediente);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudianteDadoIdExpediente_ObtenerEstudianteDadoIdExpediente_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct _myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct.getObtenerEstudianteDadoIdExpedienteReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerNiveles
     */
    public clases.entidades.Nivel[] obtenerNiveles()
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerNiveles_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerNiveles_RequestStruct _myWs_pregradoPortType_ObtenerNiveles_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerNiveles_RequestStruct();
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerNiveles_ObtenerNiveles_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerNiveles_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerNiveles_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerNiveles_ResponseStruct _myWs_pregradoPortType_ObtenerNiveles_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerNiveles_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerNiveles_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerNiveles_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerNiveles_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerNiveles_ResponseStruct.getObtenerNivelesReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerFacultades
     */
    public clases.entidades.Area[] obtenerFacultades()
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerFacultades_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerFacultades_RequestStruct _myWs_pregradoPortType_ObtenerFacultades_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerFacultades_RequestStruct();
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerFacultades_ObtenerFacultades_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerFacultades_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerFacultades_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerFacultades_ResponseStruct _myWs_pregradoPortType_ObtenerFacultades_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerFacultades_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerFacultades_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerFacultades_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerFacultades_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerFacultades_ResponseStruct.getObtenerFacultadesReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerGrupoDadoIdGrupo
     */
    public clases.entidades.Grupo obtenerGrupoDadoIdGrupo(java.lang.String idGrupo)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerGrupoDadoIdGrupo_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct _myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct.setIdGrupo(idGrupo);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerGrupoDadoIdGrupo_ObtenerGrupoDadoIdGrupo_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct _myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct.getObtenerGrupoDadoIdGrupoReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstudiantesDadoIdGrupo
     */
    public clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdGrupo(java.lang.String idGrupo)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudiantesDadoIdGrupo_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct.setIdGrupo(idGrupo);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoIdGrupo_ObtenerEstudiantesDadoIdGrupo_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct.getObtenerEstudiantesDadoIdGrupoReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstudiantesDadoIdExpedienteProfesor
     */
    public clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdExpedienteProfesor(java.lang.String idExpedienteProfesor)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudiantesDadoIdExpedienteProfesor_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct.setIdExpedienteProfesor(idExpedienteProfesor);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_ObtenerEstudiantesDadoIdExpedienteProfesor_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct.getObtenerEstudiantesDadoIdExpedienteProfesorReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstudiantes
     */
    public clases.entidades.Estudiante[] obtenerEstudiantes()
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudiantes_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_RequestStruct _myWs_pregradoPortType_ObtenerEstudiantes_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_RequestStruct();
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantes_ObtenerEstudiantes_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudiantes_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudiantes_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct _myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct.getObtenerEstudiantesReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstudianteDadoCI
     */
    public clases.entidades.Estudiante obtenerEstudianteDadoCI(java.lang.String CI)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudianteDadoCI_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct _myWs_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct.setCI(CI);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudianteDadoCI_ObtenerEstudianteDadoCI_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct _myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct.getObtenerEstudianteDadoCIReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerGrupos
     */
    public clases.entidades.Grupo[] obtenerGrupos()
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerGrupos_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerGrupos_RequestStruct _myWs_pregradoPortType_ObtenerGrupos_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerGrupos_RequestStruct();
            
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerGrupos_ObtenerGrupos_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerGrupos_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerGrupos_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerGrupos_ResponseStruct _myWs_pregradoPortType_ObtenerGrupos_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerGrupos_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerGrupos_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerGrupos_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerGrupos_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerGrupos_ResponseStruct.getObtenerGruposReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerEstudiantesDadoFiltro
     */
    public clases.entidades.Estudiante[] obtenerEstudiantesDadoFiltro(java.lang.Object filtro)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerEstudiantesDadoFiltro_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct.setFiltro(filtro);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoFiltro_ObtenerEstudiantesDadoFiltro_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct _myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct.getObtenerEstudiantesDadoFiltroReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerNivelDadoIdNivel
     */
    public clases.entidades.Nivel obtenerNivelDadoIdNivel(java.lang.String idNivel)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerNivelDadoIdNivel_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct _myWs_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct.setIdNivel(idNivel);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerNivelDadoIdNivel_ObtenerNivelDadoIdNivel_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct _myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct.getObtenerNivelDadoIdNivelReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerGruposDadoIdArea
     */
    public clases.entidades.Grupo[] obtenerGruposDadoIdArea(java.lang.String idArea)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerGruposDadoIdArea_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct _myWs_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct.setIdArea(idArea);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerGruposDadoIdArea_ObtenerGruposDadoIdArea_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct _myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct.getObtenerGruposDadoIdAreaReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of obtenerFacultadDadoIdArea
     */
    public clases.entidades.Area obtenerFacultadDadoIdArea(java.lang.String idArea)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(ObtenerFacultadDadoIdArea_OPCODE);
            wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct _myWs_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct =
                new wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct();
            
            _myWs_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct.setIdArea(idArea);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_ObtenerFacultadDadoIdArea_ObtenerFacultadDadoIdArea_QNAME);
            _bodyBlock.setValue(_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct);
            _bodyBlock.setSerializer(ns1_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "urn:ws_pregradoAction");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct _myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct =
                    (wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct)_responseObj;
            }
            
            return _myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct.getObtenerFacultadDadoIdAreaReturn();
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case ObtenerEstudiantesDadoCadenaBusqueda_OPCODE:
                _deserialize_ObtenerEstudiantesDadoCadenaBusqueda(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstados_OPCODE:
                _deserialize_ObtenerEstados(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstudianteDadoIdExpediente_OPCODE:
                _deserialize_ObtenerEstudianteDadoIdExpediente(bodyReader, deserializationContext, state);
                break;
            case ObtenerNiveles_OPCODE:
                _deserialize_ObtenerNiveles(bodyReader, deserializationContext, state);
                break;
            case ObtenerFacultades_OPCODE:
                _deserialize_ObtenerFacultades(bodyReader, deserializationContext, state);
                break;
            case ObtenerGrupoDadoIdGrupo_OPCODE:
                _deserialize_ObtenerGrupoDadoIdGrupo(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstudiantesDadoIdGrupo_OPCODE:
                _deserialize_ObtenerEstudiantesDadoIdGrupo(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstudiantesDadoIdExpedienteProfesor_OPCODE:
                _deserialize_ObtenerEstudiantesDadoIdExpedienteProfesor(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstudiantes_OPCODE:
                _deserialize_ObtenerEstudiantes(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstudianteDadoCI_OPCODE:
                _deserialize_ObtenerEstudianteDadoCI(bodyReader, deserializationContext, state);
                break;
            case ObtenerGrupos_OPCODE:
                _deserialize_ObtenerGrupos(bodyReader, deserializationContext, state);
                break;
            case ObtenerEstudiantesDadoFiltro_OPCODE:
                _deserialize_ObtenerEstudiantesDadoFiltro(bodyReader, deserializationContext, state);
                break;
            case ObtenerNivelDadoIdNivel_OPCODE:
                _deserialize_ObtenerNivelDadoIdNivel(bodyReader, deserializationContext, state);
                break;
            case ObtenerGruposDadoIdArea_OPCODE:
                _deserialize_ObtenerGruposDadoIdArea(bodyReader, deserializationContext, state);
                break;
            case ObtenerFacultadDadoIdArea_OPCODE:
                _deserialize_ObtenerFacultadDadoIdArea(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the ObtenerEstudiantesDadoCadenaBusqueda operation.
     */
    private void _deserialize_ObtenerEstudiantesDadoCadenaBusqueda(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudiantesDadoCadenaBusqueda_ObtenerEstudiantesDadoCadenaBusquedaResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoCadenaBusqueda_ObtenerEstudiantesDadoCadenaBusquedaResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstados operation.
     */
    private void _deserialize_ObtenerEstados(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstados_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstados_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstados_ObtenerEstadosResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstados_ObtenerEstadosResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstados_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstudianteDadoIdExpediente operation.
     */
    private void _deserialize_ObtenerEstudianteDadoIdExpediente(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudianteDadoIdExpediente_ObtenerEstudianteDadoIdExpedienteResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudianteDadoIdExpediente_ObtenerEstudianteDadoIdExpedienteResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerNiveles operation.
     */
    private void _deserialize_ObtenerNiveles(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerNiveles_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerNiveles_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerNiveles_ObtenerNivelesResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerNiveles_ObtenerNivelesResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerNiveles_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerFacultades operation.
     */
    private void _deserialize_ObtenerFacultades(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerFacultades_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerFacultades_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerFacultades_ObtenerFacultadesResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerFacultades_ObtenerFacultadesResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerFacultades_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerGrupoDadoIdGrupo operation.
     */
    private void _deserialize_ObtenerGrupoDadoIdGrupo(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerGrupoDadoIdGrupo_ObtenerGrupoDadoIdGrupoResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerGrupoDadoIdGrupo_ObtenerGrupoDadoIdGrupoResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstudiantesDadoIdGrupo operation.
     */
    private void _deserialize_ObtenerEstudiantesDadoIdGrupo(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudiantesDadoIdGrupo_ObtenerEstudiantesDadoIdGrupoResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoIdGrupo_ObtenerEstudiantesDadoIdGrupoResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstudiantesDadoIdExpedienteProfesor operation.
     */
    private void _deserialize_ObtenerEstudiantesDadoIdExpedienteProfesor(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_ObtenerEstudiantesDadoIdExpedienteProfesorResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_ObtenerEstudiantesDadoIdExpedienteProfesorResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstudiantes operation.
     */
    private void _deserialize_ObtenerEstudiantes(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudiantes_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudiantes_ObtenerEstudiantesResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantes_ObtenerEstudiantesResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudiantes_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstudianteDadoCI operation.
     */
    private void _deserialize_ObtenerEstudianteDadoCI(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudianteDadoCI_ObtenerEstudianteDadoCIResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudianteDadoCI_ObtenerEstudianteDadoCIResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerGrupos operation.
     */
    private void _deserialize_ObtenerGrupos(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerGrupos_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerGrupos_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerGrupos_ObtenerGruposResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerGrupos_ObtenerGruposResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerGrupos_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerEstudiantesDadoFiltro operation.
     */
    private void _deserialize_ObtenerEstudiantesDadoFiltro(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerEstudiantesDadoFiltro_ObtenerEstudiantesDadoFiltroResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerEstudiantesDadoFiltro_ObtenerEstudiantesDadoFiltroResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerNivelDadoIdNivel operation.
     */
    private void _deserialize_ObtenerNivelDadoIdNivel(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerNivelDadoIdNivel_ObtenerNivelDadoIdNivelResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerNivelDadoIdNivel_ObtenerNivelDadoIdNivelResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerGruposDadoIdArea operation.
     */
    private void _deserialize_ObtenerGruposDadoIdArea(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerGruposDadoIdArea_ObtenerGruposDadoIdAreaResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerGruposDadoIdArea_ObtenerGruposDadoIdAreaResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the ObtenerFacultadDadoIdArea operation.
     */
    private void _deserialize_ObtenerFacultadDadoIdArea(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStructObj =
            ns1_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct_SOAPSerializer.deserialize(ns1_ObtenerFacultadDadoIdArea_ObtenerFacultadDadoIdAreaResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_ObtenerFacultadDadoIdArea_ObtenerFacultadDadoIdAreaResponse_QNAME);
        bodyBlock.setValue(myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    public java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myWs_pregradoPortType_ObtenerEstados_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstados_RequestStruct.class, ns1_ObtenerEstados_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct.class, ns1_ObtenerEstudianteDadoIdExpediente_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct.class, ns1_ObtenerGruposDadoIdAreaResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerNiveles_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerNiveles_ResponseStruct.class, ns1_ObtenerNivelesResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct.class, ns1_ObtenerEstudiantesDadoCadenaBusquedaResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct.class, ns1_ObtenerEstudiantesResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct.class, ns1_ObtenerFacultadDadoIdArea_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct.class, ns1_ObtenerEstudiantesDadoIdGrupo_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct.class, ns1_ObtenerGrupoDadoIdGrupo_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerGrupos_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerGrupos_ResponseStruct.class, ns1_ObtenerGruposResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantes_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantes_RequestStruct.class, ns1_ObtenerEstudiantes_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct.class, ns1_ObtenerGruposDadoIdArea_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerFacultades_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerFacultades_RequestStruct.class, ns1_ObtenerFacultades_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct.class, ns1_ObtenerFacultadDadoIdAreaResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct.class, ns1_ObtenerEstudianteDadoCIResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct.class, ns1_ObtenerEstudiantesDadoIdGrupoResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct.class, ns1_ObtenerEstudiantesDadoIdExpedienteProfesorResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct.class, ns1_ObtenerEstudiantesDadoFiltroResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct.class, ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerNiveles_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerNiveles_RequestStruct.class, ns1_ObtenerNiveles_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstados_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstados_ResponseStruct.class, ns1_ObtenerEstadosResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct.class, ns1_ObtenerNivelDadoIdNivel_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct.class, ns1_ObtenerEstudiantesDadoFiltro_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct.class, ns1_ObtenerEstudianteDadoIdExpedienteResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct.class, ns1_ObtenerNivelDadoIdNivelResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerGrupos_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerGrupos_RequestStruct.class, ns1_ObtenerGrupos_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct.class, ns1_ObtenerGrupoDadoIdGrupoResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct.class, ns1_ObtenerEstudianteDadoCI_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerFacultades_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerFacultades_ResponseStruct.class, ns1_ObtenerFacultadesResponse_TYPE_QNAME);
        ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, wspregrado.Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct.class, ns1_ObtenerEstudiantesDadoCadenaBusqueda_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("urn:pregrado", "ws_pregradoPort");
    private static final int ObtenerEstudiantesDadoCadenaBusqueda_OPCODE = 0;
    private static final int ObtenerEstados_OPCODE = 1;
    private static final int ObtenerEstudianteDadoIdExpediente_OPCODE = 2;
    private static final int ObtenerNiveles_OPCODE = 3;
    private static final int ObtenerFacultades_OPCODE = 4;
    private static final int ObtenerGrupoDadoIdGrupo_OPCODE = 5;
    private static final int ObtenerEstudiantesDadoIdGrupo_OPCODE = 6;
    private static final int ObtenerEstudiantesDadoIdExpedienteProfesor_OPCODE = 7;
    private static final int ObtenerEstudiantes_OPCODE = 8;
    private static final int ObtenerEstudianteDadoCI_OPCODE = 9;
    private static final int ObtenerGrupos_OPCODE = 10;
    private static final int ObtenerEstudiantesDadoFiltro_OPCODE = 11;
    private static final int ObtenerNivelDadoIdNivel_OPCODE = 12;
    private static final int ObtenerGruposDadoIdArea_OPCODE = 13;
    private static final int ObtenerFacultadDadoIdArea_OPCODE = 14;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoCadenaBusqueda_ObtenerEstudiantesDadoCadenaBusqueda_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoCadenaBusqueda");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoCadenaBusqueda_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoCadenaBusqueda");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoCadenaBusqueda_ObtenerEstudiantesDadoCadenaBusquedaResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoCadenaBusquedaResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoCadenaBusquedaResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoCadenaBusquedaResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstados_ObtenerEstados_QNAME = new QName("urn:pregrado", "ObtenerEstados");
    private static final javax.xml.namespace.QName ns1_ObtenerEstados_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstados");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstados_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstados_ObtenerEstadosResponse_QNAME = new QName("urn:pregrado", "ObtenerEstadosResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstadosResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstadosResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstados_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoIdExpediente_ObtenerEstudianteDadoIdExpediente_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoIdExpediente");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoIdExpediente_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoIdExpediente");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoIdExpediente_ObtenerEstudianteDadoIdExpedienteResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoIdExpedienteResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoIdExpedienteResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoIdExpedienteResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerNiveles_ObtenerNiveles_QNAME = new QName("urn:pregrado", "ObtenerNiveles");
    private static final javax.xml.namespace.QName ns1_ObtenerNiveles_TYPE_QNAME = new QName("urn:pregrado", "ObtenerNiveles");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerNiveles_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerNiveles_ObtenerNivelesResponse_QNAME = new QName("urn:pregrado", "ObtenerNivelesResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerNivelesResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerNivelesResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerNiveles_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerFacultades_ObtenerFacultades_QNAME = new QName("urn:pregrado", "ObtenerFacultades");
    private static final javax.xml.namespace.QName ns1_ObtenerFacultades_TYPE_QNAME = new QName("urn:pregrado", "ObtenerFacultades");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerFacultades_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerFacultades_ObtenerFacultadesResponse_QNAME = new QName("urn:pregrado", "ObtenerFacultadesResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerFacultadesResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerFacultadesResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerFacultades_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerGrupoDadoIdGrupo_ObtenerGrupoDadoIdGrupo_QNAME = new QName("urn:pregrado", "ObtenerGrupoDadoIdGrupo");
    private static final javax.xml.namespace.QName ns1_ObtenerGrupoDadoIdGrupo_TYPE_QNAME = new QName("urn:pregrado", "ObtenerGrupoDadoIdGrupo");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerGrupoDadoIdGrupo_ObtenerGrupoDadoIdGrupoResponse_QNAME = new QName("urn:pregrado", "ObtenerGrupoDadoIdGrupoResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerGrupoDadoIdGrupoResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerGrupoDadoIdGrupoResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerGrupoDadoIdGrupo_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdGrupo_ObtenerEstudiantesDadoIdGrupo_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdGrupo");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdGrupo_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdGrupo");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdGrupo_ObtenerEstudiantesDadoIdGrupoResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdGrupoResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdGrupoResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdGrupoResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_ObtenerEstudiantesDadoIdExpedienteProfesor_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdExpedienteProfesor");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdExpedienteProfesor");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdExpedienteProfesor_ObtenerEstudiantesDadoIdExpedienteProfesorResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdExpedienteProfesorResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoIdExpedienteProfesorResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoIdExpedienteProfesorResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantes_ObtenerEstudiantes_QNAME = new QName("urn:pregrado", "ObtenerEstudiantes");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantes_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantes");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantes_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantes_ObtenerEstudiantesResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantes_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoCI_ObtenerEstudianteDadoCI_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoCI");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoCI_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoCI");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoCI_ObtenerEstudianteDadoCIResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoCIResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudianteDadoCIResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudianteDadoCIResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerGrupos_ObtenerGrupos_QNAME = new QName("urn:pregrado", "ObtenerGrupos");
    private static final javax.xml.namespace.QName ns1_ObtenerGrupos_TYPE_QNAME = new QName("urn:pregrado", "ObtenerGrupos");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerGrupos_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerGrupos_ObtenerGruposResponse_QNAME = new QName("urn:pregrado", "ObtenerGruposResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerGruposResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerGruposResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerGrupos_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoFiltro_ObtenerEstudiantesDadoFiltro_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoFiltro");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoFiltro_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoFiltro");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoFiltro_ObtenerEstudiantesDadoFiltroResponse_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoFiltroResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerEstudiantesDadoFiltroResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerEstudiantesDadoFiltroResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerEstudiantesDadoFiltro_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerNivelDadoIdNivel_ObtenerNivelDadoIdNivel_QNAME = new QName("urn:pregrado", "ObtenerNivelDadoIdNivel");
    private static final javax.xml.namespace.QName ns1_ObtenerNivelDadoIdNivel_TYPE_QNAME = new QName("urn:pregrado", "ObtenerNivelDadoIdNivel");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerNivelDadoIdNivel_ObtenerNivelDadoIdNivelResponse_QNAME = new QName("urn:pregrado", "ObtenerNivelDadoIdNivelResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerNivelDadoIdNivelResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerNivelDadoIdNivelResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerGruposDadoIdArea_ObtenerGruposDadoIdArea_QNAME = new QName("urn:pregrado", "ObtenerGruposDadoIdArea");
    private static final javax.xml.namespace.QName ns1_ObtenerGruposDadoIdArea_TYPE_QNAME = new QName("urn:pregrado", "ObtenerGruposDadoIdArea");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerGruposDadoIdArea_ObtenerGruposDadoIdAreaResponse_QNAME = new QName("urn:pregrado", "ObtenerGruposDadoIdAreaResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerGruposDadoIdAreaResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerGruposDadoIdAreaResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerGruposDadoIdArea_ResponseStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerFacultadDadoIdArea_ObtenerFacultadDadoIdArea_QNAME = new QName("urn:pregrado", "ObtenerFacultadDadoIdArea");
    private static final javax.xml.namespace.QName ns1_ObtenerFacultadDadoIdArea_TYPE_QNAME = new QName("urn:pregrado", "ObtenerFacultadDadoIdArea");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_ObtenerFacultadDadoIdArea_ObtenerFacultadDadoIdAreaResponse_QNAME = new QName("urn:pregrado", "ObtenerFacultadDadoIdAreaResponse");
    private static final javax.xml.namespace.QName ns1_ObtenerFacultadDadoIdAreaResponse_TYPE_QNAME = new QName("urn:pregrado", "ObtenerFacultadDadoIdAreaResponse");
    private CombinedSerializer ns1_myWs_pregradoPortType_ObtenerFacultadDadoIdArea_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "urn:pregrado"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
