// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct {
    protected java.lang.String idArea;
    
    public Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerGruposDadoIdArea_RequestStruct(java.lang.String idArea) {
        this.idArea = idArea;
    }
    
    public java.lang.String getIdArea() {
        return idArea;
    }
    
    public void setIdArea(java.lang.String idArea) {
        this.idArea = idArea;
    }
}
