// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct {
    protected java.lang.String idExpedienteProfesor;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdExpedienteProfesor_RequestStruct(java.lang.String idExpedienteProfesor) {
        this.idExpedienteProfesor = idExpedienteProfesor;
    }
    
    public java.lang.String getIdExpedienteProfesor() {
        return idExpedienteProfesor;
    }
    
    public void setIdExpedienteProfesor(java.lang.String idExpedienteProfesor) {
        this.idExpedienteProfesor = idExpedienteProfesor;
    }
}
