// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct {
    protected clases.entidades.Estudiante[] obtenerEstudiantesReturn;
    
    public Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantes_ResponseStruct(clases.entidades.Estudiante[] obtenerEstudiantesReturn) {
        this.obtenerEstudiantesReturn = obtenerEstudiantesReturn;
    }
    
    public clases.entidades.Estudiante[] getObtenerEstudiantesReturn() {
        return obtenerEstudiantesReturn;
    }
    
    public void setObtenerEstudiantesReturn(clases.entidades.Estudiante[] obtenerEstudiantesReturn) {
        this.obtenerEstudiantesReturn = obtenerEstudiantesReturn;
    }
}
