// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct {
    protected clases.entidades.Nivel obtenerNivelDadoIdNivelReturn;
    
    public Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerNivelDadoIdNivel_ResponseStruct(clases.entidades.Nivel obtenerNivelDadoIdNivelReturn) {
        this.obtenerNivelDadoIdNivelReturn = obtenerNivelDadoIdNivelReturn;
    }
    
    public clases.entidades.Nivel getObtenerNivelDadoIdNivelReturn() {
        return obtenerNivelDadoIdNivelReturn;
    }
    
    public void setObtenerNivelDadoIdNivelReturn(clases.entidades.Nivel obtenerNivelDadoIdNivelReturn) {
        this.obtenerNivelDadoIdNivelReturn = obtenerNivelDadoIdNivelReturn;
    }
}
