// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct {
    protected clases.entidades.Estudiante[] obtenerEstudiantesDadoCadenaBusquedaReturn;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_ResponseStruct(clases.entidades.Estudiante[] obtenerEstudiantesDadoCadenaBusquedaReturn) {
        this.obtenerEstudiantesDadoCadenaBusquedaReturn = obtenerEstudiantesDadoCadenaBusquedaReturn;
    }
    
    public clases.entidades.Estudiante[] getObtenerEstudiantesDadoCadenaBusquedaReturn() {
        return obtenerEstudiantesDadoCadenaBusquedaReturn;
    }
    
    public void setObtenerEstudiantesDadoCadenaBusquedaReturn(clases.entidades.Estudiante[] obtenerEstudiantesDadoCadenaBusquedaReturn) {
        this.obtenerEstudiantesDadoCadenaBusquedaReturn = obtenerEstudiantesDadoCadenaBusquedaReturn;
    }
}
