// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct {
    protected java.lang.String idNivel;
    
    public Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerNivelDadoIdNivel_RequestStruct(java.lang.String idNivel) {
        this.idNivel = idNivel;
    }
    
    public java.lang.String getIdNivel() {
        return idNivel;
    }
    
    public void setIdNivel(java.lang.String idNivel) {
        this.idNivel = idNivel;
    }
}
