// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct {
    protected clases.entidades.Estudiante obtenerEstudianteDadoCIReturn;
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoCI_ResponseStruct(clases.entidades.Estudiante obtenerEstudianteDadoCIReturn) {
        this.obtenerEstudianteDadoCIReturn = obtenerEstudianteDadoCIReturn;
    }
    
    public clases.entidades.Estudiante getObtenerEstudianteDadoCIReturn() {
        return obtenerEstudianteDadoCIReturn;
    }
    
    public void setObtenerEstudianteDadoCIReturn(clases.entidades.Estudiante obtenerEstudianteDadoCIReturn) {
        this.obtenerEstudianteDadoCIReturn = obtenerEstudianteDadoCIReturn;
    }
}
