// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerGrupos_ResponseStruct {
    protected clases.entidades.Grupo[] obtenerGruposReturn;
    
    public Ws_pregradoPortType_ObtenerGrupos_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerGrupos_ResponseStruct(clases.entidades.Grupo[] obtenerGruposReturn) {
        this.obtenerGruposReturn = obtenerGruposReturn;
    }
    
    public clases.entidades.Grupo[] getObtenerGruposReturn() {
        return obtenerGruposReturn;
    }
    
    public void setObtenerGruposReturn(clases.entidades.Grupo[] obtenerGruposReturn) {
        this.obtenerGruposReturn = obtenerGruposReturn;
    }
}
