// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct {
    protected java.lang.String CI;
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoCI_RequestStruct(java.lang.String CI) {
        this.CI = CI;
    }
    
    public java.lang.String getCI() {
        return CI;
    }
    
    public void setCI(java.lang.String CI) {
        this.CI = CI;
    }
}
