// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct {
    protected clases.entidades.Estudiante obtenerEstudianteDadoIdExpedienteReturn;
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_ResponseStruct(clases.entidades.Estudiante obtenerEstudianteDadoIdExpedienteReturn) {
        this.obtenerEstudianteDadoIdExpedienteReturn = obtenerEstudianteDadoIdExpedienteReturn;
    }
    
    public clases.entidades.Estudiante getObtenerEstudianteDadoIdExpedienteReturn() {
        return obtenerEstudianteDadoIdExpedienteReturn;
    }
    
    public void setObtenerEstudianteDadoIdExpedienteReturn(clases.entidades.Estudiante obtenerEstudianteDadoIdExpedienteReturn) {
        this.obtenerEstudianteDadoIdExpedienteReturn = obtenerEstudianteDadoIdExpedienteReturn;
    }
}
