// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct {
    protected java.lang.String idGrupo;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_RequestStruct(java.lang.String idGrupo) {
        this.idGrupo = idGrupo;
    }
    
    public java.lang.String getIdGrupo() {
        return idGrupo;
    }
    
    public void setIdGrupo(java.lang.String idGrupo) {
        this.idGrupo = idGrupo;
    }
}
