// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct {
    protected java.lang.String idExpediente;
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudianteDadoIdExpediente_RequestStruct(java.lang.String idExpediente) {
        this.idExpediente = idExpediente;
    }
    
    public java.lang.String getIdExpediente() {
        return idExpediente;
    }
    
    public void setIdExpediente(java.lang.String idExpediente) {
        this.idExpediente = idExpediente;
    }
}
