// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct {
    protected java.lang.String cadena;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoCadenaBusqueda_RequestStruct(java.lang.String cadena) {
        this.cadena = cadena;
    }
    
    public java.lang.String getCadena() {
        return cadena;
    }
    
    public void setCadena(java.lang.String cadena) {
        this.cadena = cadena;
    }
}
