// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerNiveles_ResponseStruct {
    protected clases.entidades.Nivel[] obtenerNivelesReturn;
    
    public Ws_pregradoPortType_ObtenerNiveles_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerNiveles_ResponseStruct(clases.entidades.Nivel[] obtenerNivelesReturn) {
        this.obtenerNivelesReturn = obtenerNivelesReturn;
    }
    
    public clases.entidades.Nivel[] getObtenerNivelesReturn() {
        return obtenerNivelesReturn;
    }
    
    public void setObtenerNivelesReturn(clases.entidades.Nivel[] obtenerNivelesReturn) {
        this.obtenerNivelesReturn = obtenerNivelesReturn;
    }
}
