// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package wspregrado;


public class Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct {
    protected clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdGrupoReturn;
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct() {
    }
    
    public Ws_pregradoPortType_ObtenerEstudiantesDadoIdGrupo_ResponseStruct(clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdGrupoReturn) {
        this.obtenerEstudiantesDadoIdGrupoReturn = obtenerEstudiantesDadoIdGrupoReturn;
    }
    
    public clases.entidades.EstudianteGrupo[] getObtenerEstudiantesDadoIdGrupoReturn() {
        return obtenerEstudiantesDadoIdGrupoReturn;
    }
    
    public void setObtenerEstudiantesDadoIdGrupoReturn(clases.entidades.EstudianteGrupo[] obtenerEstudiantesDadoIdGrupoReturn) {
        this.obtenerEstudiantesDadoIdGrupoReturn = obtenerEstudiantesDadoIdGrupoReturn;
    }
}
