// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3
package clases.entidades;

import clases.entidades.abstracts.AbstractGrupos;

public class Area extends AbstractGrupos<Nivel>{

    protected java.lang.String idArea;
    protected java.lang.String nombreArea;


    public Area() {
    }

    public Area(java.lang.String idArea, java.lang.String nombreArea) {
        this.idArea = idArea;
        this.nombreArea = nombreArea;
    }

    public java.lang.String getIdArea() {
        return idArea;
    }

    public void setIdArea(java.lang.String idArea) {
        this.idArea = idArea;
    }

    public java.lang.String getNombreArea() {
        return nombreArea;
    }

    public void setNombreArea(java.lang.String nombreArea) {
        this.nombreArea = nombreArea;
    }

    @Override
    public String toString() {
        return nombreArea;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.idArea != null ? this.idArea.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Area other = (Area) obj;
        if ((this.idArea == null) ? (other.idArea != null) : !this.idArea.equals(other.idArea)) {
            return false;
        }
        return true;
    }
    
    
}
