// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package clases.entidades;


public class CategoriaPersona {
    protected java.lang.String idCategoria;
    protected java.lang.String nombreCategoria;
    
    public CategoriaPersona() {
    }
    
    public CategoriaPersona(java.lang.String idCategoria, java.lang.String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    
    public java.lang.String getIdCategoria() {
        return idCategoria;
    }
    
    public void setIdCategoria(java.lang.String idCategoria) {
        this.idCategoria = idCategoria;
    }
    
    public java.lang.String getNombreCategoria() {
        return nombreCategoria;
    }
    
    public void setNombreCategoria(java.lang.String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.idCategoria != null ? this.idCategoria.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final CategoriaPersona other = (CategoriaPersona) obj;
        if ((this.idCategoria == null) ? (other.idCategoria != null) : !this.idCategoria.equals(other.idCategoria)) {
            return false;
        }
        return true;
    }
    
    
}
