// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package clases.entidades;


public class Estado {
    protected java.lang.String idEstado;
    protected java.lang.String nombreEstado;
    
    public Estado() {
    }
    
    public Estado(java.lang.String idEstado, java.lang.String nombreEstado) {
        this.idEstado = idEstado;
        this.nombreEstado = nombreEstado;
    }
    
    public java.lang.String getIdEstado() {
        return idEstado;
    }
    
    public void setIdEstado(java.lang.String idEstado) {
        this.idEstado = idEstado;
    }
    
    public java.lang.String getNombreEstado() {
        return nombreEstado;
    }
    
    public void setNombreEstado(java.lang.String nombreEstado) {
        this.nombreEstado = nombreEstado;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 41 * hash + (this.idEstado != null ? this.idEstado.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Estado other = (Estado) obj;
        if ((this.idEstado == null) ? (other.idEstado != null) : !this.idEstado.equals(other.idEstado)) {
            return false;
        }
        return true;
    }
    
    
}
