// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3
package clases.entidades;

import clases.connexion.LDAPCon;
import clases.entidades.abstracts.Seleccionable;
import clases.entidades.interfaces.Receiver;
import java.io.Serializable;
import javax.naming.NamingException;

public class Estudiante extends Seleccionable implements Receiver, Serializable,Cloneable {

    protected String uid;
    protected java.lang.String idExpediente;
    protected java.lang.String primerNombre;
    protected java.lang.String segundoNombre;
    protected java.lang.String primerApellido;
    protected java.lang.String segundoApellido;
    protected java.lang.String CI;
    protected clases.entidades.Estado estado;
    protected java.lang.String genero;
    protected clases.entidades.Municipio municipio;
    protected clases.entidades.CategoriaPersona categoriaPersona;
    protected clases.entidades.Area area;
    protected clases.entidades.Grupo grupo;
    protected clases.entidades.Nivel nivel;

    public Estudiante() {
    }

    public Estudiante(String uid, String CI) {
        this.uid = uid;
        this.CI = CI;
    }

    public Estudiante(java.lang.String idExpediente, java.lang.String primerNombre, java.lang.String segundoNombre, java.lang.String primerApellido, java.lang.String segundoApellido, java.lang.String CI, clases.entidades.Estado estado, java.lang.String genero, clases.entidades.Municipio municipio, clases.entidades.CategoriaPersona categoriaPersona, clases.entidades.Area area, clases.entidades.Grupo grupo, clases.entidades.Nivel nivel) {
        this.idExpediente = idExpediente;
        this.primerNombre = primerNombre;
        this.segundoNombre = segundoNombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.CI = CI;
        this.estado = estado;
        this.genero = genero;
        this.municipio = municipio;
        this.categoriaPersona = categoriaPersona;
        this.area = area;
        this.grupo = grupo;
        this.nivel = nivel;
    }

    @Override
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public java.lang.String getIdExpediente() {
        return idExpediente;
    }

    public void setIdExpediente(java.lang.String idExpediente) {
        this.idExpediente = idExpediente;
    }

    public java.lang.String getPrimerNombre() {
        return primerNombre;
    }

    public void setPrimerNombre(java.lang.String primerNombre) {
        this.primerNombre = primerNombre;
    }

    public java.lang.String getSegundoNombre() {
        return segundoNombre;
    }

    public void setSegundoNombre(java.lang.String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    public java.lang.String getPrimerApellido() {
        return primerApellido;
    }

    public void setPrimerApellido(java.lang.String primerApellido) {
        this.primerApellido = primerApellido;
    }

    public java.lang.String getSegundoApellido() {
        return segundoApellido;
    }

    public void setSegundoApellido(java.lang.String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    public java.lang.String getCI() {
        return CI;
    }

    public void setCI(java.lang.String CI) {
        this.CI = CI;
    }

    public clases.entidades.Estado getEstado() {
        return estado;
    }

    public void setEstado(clases.entidades.Estado estado) {
        this.estado = estado;
    }

    public java.lang.String getGenero() {
        return genero;
    }

    public void setGenero(java.lang.String genero) {
        this.genero = genero;
    }

    public clases.entidades.Municipio getMunicipio() {
        return municipio;
    }

    public void setMunicipio(clases.entidades.Municipio municipio) {
        this.municipio = municipio;
    }

    public clases.entidades.CategoriaPersona getCategoriaPersona() {
        return categoriaPersona;
    }

    public void setCategoriaPersona(clases.entidades.CategoriaPersona categoriaPersona) {
        this.categoriaPersona = categoriaPersona;
    }

    public clases.entidades.Area getArea() {
        return area;
    }

    public void setArea(clases.entidades.Area area) {
        this.area = area;
    }

    public clases.entidades.Grupo getGrupo() {
        return grupo;
    }

    public void setGrupo(clases.entidades.Grupo grupo) {
        this.grupo = grupo;
    }

    public clases.entidades.Nivel getNivel() {
        return nivel;
    }

    public void setNivel(clases.entidades.Nivel nivel) {
        this.nivel = nivel;
    }

    public void updateUid() throws NamingException {
        if (uid == null && "Matriculado".equals(estado.nombreEstado)) {
            uid = LDAPCon.getInstance().getUID(primerNombre + (segundoNombre.length() > 0 ? " " + segundoNombre : "") + " " + primerApellido + " " + segundoApellido);
        }
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + (this.CI != null ? this.CI.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Estudiante other = (Estudiante) obj;
        if ((this.CI == null) ? (other.CI != null) : !this.CI.equals(other.CI)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return primerNombre + " " + segundoNombre + " " + primerApellido + " " + segundoApellido;
    }

}
