// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3
package clases.entidades;

public class EstudianteGrupo {

    protected java.lang.String noExpediente;
    protected java.lang.String PNombre;
    protected java.lang.String SNombre;
    protected java.lang.String PApellido;
    protected java.lang.String SApellido;
    protected java.lang.String CI;
    protected java.lang.String idGrupo;
    protected java.lang.String grupo;
    protected java.lang.String idFacultad;
    protected java.lang.String facultad;

    public EstudianteGrupo() {
    }

    public EstudianteGrupo(java.lang.String noExpediente, java.lang.String PNombre, java.lang.String SNombre, java.lang.String PApellido, java.lang.String SApellido, java.lang.String CI, java.lang.String idGrupo, java.lang.String grupo, java.lang.String idFacultad, java.lang.String facultad) {
        this.noExpediente = noExpediente;
        this.PNombre = PNombre;
        this.SNombre = SNombre;
        this.PApellido = PApellido;
        this.SApellido = SApellido;
        this.CI = CI;
        this.idGrupo = idGrupo;
        this.grupo = grupo;
        this.idFacultad = idFacultad;
        this.facultad = facultad;
    }

    public java.lang.String getNoExpediente() {
        return noExpediente;
    }

    public void setNoExpediente(java.lang.String noExpediente) {
        this.noExpediente = noExpediente;
    }

    public java.lang.String getPNombre() {
        return PNombre;
    }

    public void setPNombre(java.lang.String PNombre) {
        this.PNombre = PNombre;
    }

    public java.lang.String getSNombre() {
        return SNombre;
    }

    public void setSNombre(java.lang.String SNombre) {
        this.SNombre = SNombre;
    }

    public java.lang.String getPApellido() {
        return PApellido;
    }

    public void setPApellido(java.lang.String PApellido) {
        this.PApellido = PApellido;
    }

    public java.lang.String getSApellido() {
        return SApellido;
    }

    public void setSApellido(java.lang.String SApellido) {
        this.SApellido = SApellido;
    }

    public java.lang.String getCI() {
        return CI;
    }

    public void setCI(java.lang.String CI) {
        this.CI = CI;
    }

    public java.lang.String getIdGrupo() {
        return idGrupo;
    }

    public void setIdGrupo(java.lang.String idGrupo) {
        this.idGrupo = idGrupo;
    }

    public java.lang.String getGrupo() {
        return grupo;
    }

    public void setGrupo(java.lang.String grupo) {
        this.grupo = grupo;
    }

    public java.lang.String getIdFacultad() {
        return idFacultad;
    }

    public void setIdFacultad(java.lang.String idFacultad) {
        this.idFacultad = idFacultad;
    }

    public java.lang.String getFacultad() {
        return facultad;
    }

    public void setFacultad(java.lang.String facultad) {
        this.facultad = facultad;
    }

    public Estudiante getEstudiante() {
        try { // This code block invokes the Ws_pregradoPort:obtenerEstudianteDadoCI operation on web service
            wspregrado.PregradoService pregradoService = new wspregrado.PregradoService_Impl();
            wspregrado.Ws_pregradoPortType _ws_pregradoPort = pregradoService.getWs_pregradoPort();
            Estudiante obtenerEstudianteDadoCI = _ws_pregradoPort.obtenerEstudianteDadoCI(CI);
            obtenerEstudianteDadoCI.updateUid();
            return obtenerEstudianteDadoCI;
        } catch (javax.xml.rpc.ServiceException ex) {
            java.util.logging.Logger.getLogger(wspregrado.PregradoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (java.rmi.RemoteException ex) {
            java.util.logging.Logger.getLogger(wspregrado.PregradoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(wspregrado.PregradoService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return null;
    }
}
