// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3

package clases.entidades;


public class Municipio {
    protected java.lang.String idMunicipio;
    protected java.lang.String idProvincia;
    protected java.lang.String nombreMunicipio;
    
    public Municipio() {
    }
    
    public Municipio(java.lang.String idMunicipio, java.lang.String idProvincia, java.lang.String nombreMunicipio) {
        this.idMunicipio = idMunicipio;
        this.idProvincia = idProvincia;
        this.nombreMunicipio = nombreMunicipio;
    }
    
    public java.lang.String getIdMunicipio() {
        return idMunicipio;
    }
    
    public void setIdMunicipio(java.lang.String idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    
    public java.lang.String getIdProvincia() {
        return idProvincia;
    }
    
    public void setIdProvincia(java.lang.String idProvincia) {
        this.idProvincia = idProvincia;
    }
    
    public java.lang.String getNombreMunicipio() {
        return nombreMunicipio;
    }
    
    public void setNombreMunicipio(java.lang.String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + (this.idMunicipio != null ? this.idMunicipio.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Municipio other = (Municipio) obj;
        if ((this.idMunicipio == null) ? (other.idMunicipio != null) : !this.idMunicipio.equals(other.idMunicipio)) {
            return false;
        }
        return true;
    }
    
    
}
