// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, compilación R1)
// Generated source version: 1.1.3
package clases.entidades;

import clases.entidades.abstracts.SelectGrupos;
import java.util.Collection;

public class Nivel extends SelectGrupos<Grupo>  {

    protected java.lang.String idNivel;
    protected java.lang.String nombreNivel;

    public Nivel() {
    }

    public Nivel(java.lang.String idNivel, java.lang.String nombreNivel) {
        this.idNivel = idNivel;
        this.nombreNivel = nombreNivel;
    }

    public java.lang.String getIdNivel() {
        return idNivel;
    }

    public void setIdNivel(java.lang.String idNivel) {
        this.idNivel = idNivel;
    }

    public java.lang.String getNombreNivel() {
        return nombreNivel;
    }

    public void setNombreNivel(java.lang.String nombreNivel) {
        this.nombreNivel = nombreNivel;
    }

    @Override
    public Collection<Grupo> getGrupos() {
        return getSelectables().values(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 23 * hash + (this.idNivel != null ? this.idNivel.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Nivel other = (Nivel) obj;
        if ((this.idNivel == null) ? (other.idNivel != null) : !this.idNivel.equals(other.idNivel)) {
            return false;
        }
        return true;
    }
    
    
    
}
